version: '3.8'

services:
  app:
    container_name: "snake_game"
    build: "./"
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - ${HOST_PORT}:8000
    env_file:
      - .env
    volumes:
      - ./:/src/app